<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamSeeder extends Seeder
{
    public function run() : Void
    {
        // NCAA teams
        DB::table('teams')->insert(['name' => 'Air Force Falcons', 'short_name' => 'Air Force', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Akron Zips', 'short_name' => 'Akron', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Alabama Crimson Tide', 'short_name' => 'Alabama', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Appalachian State Mountaineers', 'short_name' => 'Appalachian State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Arizona State Sun Devils', 'short_name' => 'Arizona State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Arizona Wildcats', 'short_name' => 'Arizona', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Arkansas Razorbacks', 'short_name' => 'Arkansas', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Arkansas State Red Wolves', 'short_name' => 'Arkansas State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Army Black Knights', 'short_name' => 'Army', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Auburn Tigers', 'short_name' => 'Auburn', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Ball State Cardinals', 'short_name' => 'Ball State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Baylor Bears', 'short_name' => 'Baylor', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Boise State Broncos', 'short_name' => 'Boise State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Boston College Eagles', 'short_name' => 'Boston College', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Bowling Green Falcons', 'short_name' => 'Bowling Green', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Buffalo Bulls', 'short_name' => 'Buffalo', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'BYU Cougars', 'short_name' => 'BYU', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'California Golden Bears', 'short_name' => 'California', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Central Michigan Chippewas', 'short_name' => 'Central Michigan', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Charlotte 49ers', 'short_name' => 'Charlotte', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Cincinnati Bearcats', 'short_name' => 'Cincinnati', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Clemson Tigers', 'short_name' => 'Clemson', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Coastal Carolina Chanticleers', 'short_name' => 'Coastal Carolina', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Colorado Buffaloes', 'short_name' => 'Colorado', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Colorado State Rams', 'short_name' => 'Colorado State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Duke Blue Devils', 'short_name' => 'Duke', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'East Carolina Pirates', 'short_name' => 'East Carolina', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Eastern Michigan Eagles', 'short_name' => 'Eastern Michigan', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Florida Atlantic Owls', 'short_name' => 'Florida Atlantic', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Florida Gators', 'short_name' => 'Florida', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Florida International Panthers', 'short_name' => 'Florida International', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Florida State Seminoles', 'short_name' => 'Florida State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Fresno State Bulldogs', 'short_name' => 'Fresno State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Georgia Bulldogs', 'short_name' => 'Georgia', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Georgia Southern Eagles', 'short_name' => 'Georgia Southern', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Georgia State Panthers', 'short_name' => 'Georgia State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Georgia Tech Yellow Jackets', 'short_name' => 'Georgia Tech', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Hawaii Rainbow Warriors', 'short_name' => 'Hawai\'i', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Houston Cougars', 'short_name' => 'Houston', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Illinois Fighting Illini', 'short_name' => 'Illinois', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Indiana Hoosiers', 'short_name' => 'Indiana', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Iowa Hawkeyes', 'short_name' => 'Iowa', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Iowa State Cyclones', 'short_name' => 'Iowa State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'James Madison Dukes', 'short_name' => 'James Madison', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Kansas Jayhawks', 'short_name' => 'Kansas', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Kansas State Wildcats', 'short_name' => 'Kansas State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Kent State Golden Flashes', 'short_name' => 'Kent State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Kentucky Wildcats', 'short_name' => 'Kentucky', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Liberty Flames', 'short_name' => 'Liberty', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Louisiana Ragin\' Cajuns', 'short_name' => 'Louisiana', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Louisiana Tech Bulldogs', 'short_name' => 'Louisiana Tech', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Louisville Cardinals', 'short_name' => 'Louisville', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'LSU Tigers', 'short_name' => 'LSU', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Marshall Thundering Herd', 'short_name' => 'Marshall', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Maryland Terrapins', 'short_name' => 'Maryland', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Memphis Tigers', 'short_name' => 'Memphis', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Miami (OH) RedHawks', 'short_name' => 'Miami (OH)', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Miami Hurricanes', 'short_name' => 'Miami (FL)', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Michigan State Spartans', 'short_name' => 'Michigan State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Michigan Wolverines', 'short_name' => 'Michigan', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Middle Tennessee Blue Raiders', 'short_name' => 'Middle Tennessee', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Minnesota Golden Gophers', 'short_name' => 'Minnesota', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Mississippi State Bulldogs', 'short_name' => 'Mississippi State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Missouri Tigers', 'short_name' => 'Missouri', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Navy Midshipmen', 'short_name' => 'Navy', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'NC State Wolfpack', 'short_name' => 'North Carolina State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Nebraska Cornhuskers', 'short_name' => 'Nebraska', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Nevada Wolf Pack', 'short_name' => 'Nevada', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'New Mexico Lobos', 'short_name' => 'New Mexico', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'New Mexico State Aggies', 'short_name' => 'New Mexico State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'North Carolina Tar Heels', 'short_name' => 'North Carolina', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'North Texas Mean Green', 'short_name' => 'North Texas', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Northern Illinois Huskies', 'short_name' => 'Northern Illinois', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Northwestern Wildcats', 'short_name' => 'Northwestern', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Notre Dame Fighting Irish', 'short_name' => 'Notre Dame', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Ohio Bobcats', 'short_name' => 'Ohio', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Ohio State Buckeyes', 'short_name' => 'Ohio State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Oklahoma Sooners', 'short_name' => 'Oklahoma', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Oklahoma State Cowboys', 'short_name' => 'Oklahoma State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Old Dominion Monarchs', 'short_name' => 'Old Dominion', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Ole Miss Rebels', 'short_name' => 'Ole Miss', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Oregon Ducks', 'short_name' => 'Oregon', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Oregon State Beavers', 'short_name' => 'Oregon State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Penn State Nittany Lions', 'short_name' => 'Penn State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Pittsburgh Panthers', 'short_name' => 'Pittsburgh', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Purdue Boilermakers', 'short_name' => 'Purdue', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Rice Owls', 'short_name' => 'Rice', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Rutgers Scarlet Knights', 'short_name' => 'Rutgers', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'San Diego State Aztecs', 'short_name' => 'San Diego State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'San José State', 'short_name' => 'San Jose State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'SMU Mustangs', 'short_name' => 'SMU', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'South Alabama Jaguars', 'short_name' => 'South Alabama', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'South Carolina Gamecocks', 'short_name' => 'South Carolina', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'South Florida Bulls', 'short_name' => 'South Florida', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Southern Mississippi Golden Eagles', 'short_name' => 'Southern Miss', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Stanford Cardinal', 'short_name' => 'Stanford', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Syracuse Orange', 'short_name' => 'Syracuse', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'TCU Horned Frogs', 'short_name' => 'TCU', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Temple Owls', 'short_name' => 'Temple', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Tennessee Volunteers', 'short_name' => 'Tennessee', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Texas A&M Aggies', 'short_name' => 'Texas A&M', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Texas Longhorns', 'short_name' => 'Texas', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Texas State Bobcats', 'short_name' => 'Texas State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Texas Tech Red Raiders', 'short_name' => 'Texas Tech', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Toledo Rockets', 'short_name' => 'Toledo', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Troy Trojans', 'short_name' => 'Troy', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Tulane Green Wave', 'short_name' => 'Tulane', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Tulsa Golden Hurricane', 'short_name' => 'Tulsa', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UAB Blazers', 'short_name' => 'UAB', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UCF Knights', 'short_name' => 'UCF', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UCLA Bruins', 'short_name' => 'UCLA', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UConn Huskies', 'short_name' => 'UConn', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UL Monroe Warhawks', 'short_name' => 'Louisiana-Monroe', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UMass Minutemen', 'short_name' => 'UMass', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UNLV Rebels', 'short_name' => 'UNLV', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'USC Trojans', 'short_name' => 'USC', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Utah State Aggies', 'short_name' => 'Utah State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Utah Utes', 'short_name' => 'Utah', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UTEP Miners', 'short_name' => 'UTEP', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'UTSA Roadrunners', 'short_name' => 'UTSA', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Vanderbilt Commodores', 'short_name' => 'Vanderbilt', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Virginia Cavaliers', 'short_name' => 'Virginia', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Virginia Tech Hokies', 'short_name' => 'Virginia Tech', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Wake Forest Demon Deacons', 'short_name' => 'Wake Forest', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Washington Huskies', 'short_name' => 'Washington', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Washington State Cougars', 'short_name' => 'Washington State', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'West Virginia Mountaineers', 'short_name' => 'West Virginia', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Western Kentucky Hilltoppers', 'short_name' => 'Western Kentucky', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Western Michigan Broncos', 'short_name' => 'Western Michigan', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Wisconsin Badgers', 'short_name' => 'Wisconsin', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Wyoming Cowboys', 'short_name' => 'Wyoming', 'league' =>' NCAA', 'created_at' => NOW(), 'updated_at' => NOW(),]);

        // NFL teams
        DB::table('teams')->insert(['name' => 'Arizona Cardinals', 'short_name' => 'ARI Cardinals', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Atlanta Falcons', 'short_name' => 'ATL Falcons', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Baltimore Ravens', 'short_name' => 'BAL Ravens', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Buffalo Bills', 'short_name' => 'BUF Bills', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Carolina Panthers', 'short_name' => 'CAR Panthers', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Chicago Bears', 'short_name' => 'CHI Bears', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Cincinnati Bengals', 'short_name' => 'CIN Bengals', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Cleveland Browns', 'short_name' => 'CLE Browns', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Dallas Cowboys', 'short_name' => 'DAL Cowboys', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Denver Broncos', 'short_name' => 'DEN Broncos', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Detroit Lions', 'short_name' => 'DET Lions', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Green Bay Packers', 'short_name' => 'GB Packers', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Houston Texans', 'short_name' => 'HOU Texans', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Indianapolis Colts', 'short_name' => 'IND Colts', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Jacksonville Jaguars', 'short_name' => 'JAX Jaguars', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Kansas City Chiefs', 'short_name' => 'KC Chiefs', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Las Vegas Raiders', 'short_name' => 'LV Raiders', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Los Angeles Chargers', 'short_name' => 'LA Chargers', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Los Angeles Rams', 'short_name' => 'LA Rams', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Miami Dolphins', 'short_name' => 'MIA Dolphins', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Minnesota Vikings', 'short_name' => 'MIN Vikings', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'New England Patriots', 'short_name' => 'NE Patriots', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'New Orleans Saints', 'short_name' => 'NO Saints', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'New York Giants', 'short_name' => 'NY Giants', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'New York Jets', 'short_name' => 'NY Jets', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Philadelphia Eagles', 'short_name' => 'PHI Eagles', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Pittsburgh Steelers', 'short_name' => 'PIT Steelers', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'San Francisco 49ers', 'short_name' => 'SF 49ers', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Seattle Seahawks', 'short_name' => 'SEA Seahawks', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Tampa Bay Buccaneers', 'short_name' => 'TB Buccaneers', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Tennessee Titans', 'short_name' => 'TEN Titans', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
        DB::table('teams')->insert(['name' => 'Washington Commanders', 'short_name' => 'WSH Commanders', 'league' => 'NFL', 'created_at' => NOW(), 'updated_at' => NOW(),]);

        // NHL teams for testing
//        DB::table('teams')->insert(['name' => 'Anaheim Ducks', 'short_name' => 'ANA Ducks', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Arizona Coyotes', 'short_name' => 'ARI Coyotes', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Boston Bruins', 'short_name' => 'BOS Bruins', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Buffalo Sabres', 'short_name' => 'BUF Sabres', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Calgary Flames', 'short_name' => 'CGY Flames', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Carolina Hurricanes', 'short_name' => 'CAR Hurricanes', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Chicago Blackhawks', 'short_name' => 'CHI Blackhawks', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Colorado Avalanche', 'short_name' => 'COL Avalanche', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Columbus Blue Jackets', 'short_name' => 'CBJ Blue Jackets', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Dallas Stars', 'short_name' => 'DAL Stars', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Detroit Red Wings', 'short_name' => 'DET Red Wings', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Edmonton Oilers', 'short_name' => 'EDM Oilers', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Florida Panthers', 'short_name' => 'FLA Panthers', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Los Angeles Kings', 'short_name' => 'LA Kings', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Minnesota Wild', 'short_name' => 'MIN Wild', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Montréal Canadiens', 'short_name' => 'MTL Canadiens', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Nashville Predators', 'short_name' => 'NSH Predators', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'New Jersey Devils', 'short_name' => 'NJ Devils', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'New York Islanders', 'short_name' => 'NY Islanders', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'New York Rangers', 'short_name' => 'NY Rangers', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Ottawa Senators', 'short_name' => 'OTT Senators', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Philadelphia Flyers', 'short_name' => 'PHI Flyers', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Pittsburgh Penguins', 'short_name' => 'PIT Penguins', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'San Jose Sharks', 'short_name' => 'SJ Sharks', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Seattle Kraken', 'short_name' => 'SEA Kraken', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'St Louis Blues', 'short_name' => 'STL Blues', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Tampa Bay Lightning', 'short_name' => 'TB Lightning', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Toronto Maple Leafs', 'short_name' => 'TOR Maple Leafs', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Vancouver Canucks', 'short_name' => 'VAN Canucks', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Vegas Golden Knights', 'short_name' => 'VGS Golden Knights', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Washington Capitals', 'short_name' => 'WSH Capitals', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Winnipeg Jets', 'short_name' => 'WPG Jets', 'league' => 'NHL', 'created_at' => NOW(), 'updated_at' => NOW(),]);

        // NBA teams for testing
//        DB::table('teams')->insert(['name' => 'Atlanta Hawks', 'short_name' => 'ATL Hawks', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Boston Celtics', 'short_name' => 'BOS Celtics', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Brooklyn Nets', 'short_name' => 'BKN Nets', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Charlotte Hornets', 'short_name' => 'CHA Hornets', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Chicago Bulls', 'short_name' => 'CHI Bulls', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Cleveland Cavaliers', 'short_name' => 'CLE Cavaliers', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Dallas Mavericks', 'short_name' => 'DAL Mavericks', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Denver Nuggets', 'short_name' => 'DEN Nuggets', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Detroit Pistons', 'short_name' => 'DET Pistons', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Golden State Warriors', 'short_name' => 'GS Warriors', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Houston Rockets', 'short_name' => 'HOU Rockets', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Indiana Pacers', 'short_name' => 'IND Pacers', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Los Angeles Clippers', 'short_name' => 'LA Clippers', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Los Angeles Lakers', 'short_name' => 'LA Lakers', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Memphis Grizzlies', 'short_name' => 'MEM Grizzlies', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Miami Heat', 'short_name' => 'MIA Heat', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Milwaukee Bucks', 'short_name' => 'MIL Bucks', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Minnesota Timberwolves', 'short_name' => 'MIN Timberwolves', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'New Orleans Pelicans', 'short_name' => 'NO Pelicans', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'New York Knicks', 'short_name' => 'NY Knicks', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Oklahoma City Thunder', 'short_name' => 'OKC Thunder', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Orlando Magic', 'short_name' => 'ORL Magic', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Philadelphia 76ers', 'short_name' => 'PHI 76ers', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Phoenix Suns', 'short_name' => 'PHX Suns', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Portland Trail Blazers', 'short_name' => 'POR Trail Blazers', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Sacramento Kings', 'short_name' => 'SAC Kings', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'San Antonio Spurs', 'short_name' => 'SA Spurs', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Toronto Raptors', 'short_name' => 'TOR Raptors', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Utah Jazz', 'short_name' => 'UTA Jazz', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Washington Wizards', 'short_name' => 'WSH Wizards', 'league' => 'NBA', 'created_at' => NOW(), 'updated_at' => NOW(),]);

        // MLB teams for testing
//        DB::table('teams')->insert(['name' => 'Arizona Diamondbacks', 'short_name' => 'ARI Diamondbacks', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Atlanta Braves', 'short_name' => 'ATL Braves', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Baltimore Orioles', 'short_name' => 'ATL Braves', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Boston Red Sox', 'short_name' => 'BOS Red Sox', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Chicago Cubs', 'short_name' => 'CHI Cubs', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Chicago White Sox', 'short_name' => 'CHI White Sox', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Cincinnati Reds', 'short_name' => 'CIN Reds', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Cleveland Guardians', 'short_name' => 'CLE Guardians', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Colorado Rockies', 'short_name' => 'COL Rockies', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Detroit Tigers', 'short_name' => 'DET Tigers', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Houston Astros', 'short_name' => 'HOU Astros', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Kansas City Royals', 'short_name' => 'KC Royals', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Los Angeles Angels', 'short_name' => 'LA Angels', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Los Angeles Dodgers', 'short_name' => 'LA Dodgers', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Miami Marlins', 'short_name' => 'MIA Marlins', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Milwaukee Brewers', 'short_name' => 'MIL Brewers', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Minnesota Twins', 'short_name' => 'MIN Twins', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'New York Mets', 'short_name' => 'NY Mets', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'New York Yankees', 'short_name' => 'NY Yankees', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Oakland Athletics', 'short_name' => 'OAK Athletics', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Philadelphia Phillies', 'short_name' => 'PHI Phillies', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Pittsburgh Pirates', 'short_name' => 'PIT Pirates', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'San Diego Padres', 'short_name' => 'SD Padres', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'San Francisco Giants', 'short_name' => 'SF Giants', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Seattle Mariners', 'short_name' => 'SEA Mariners', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'St. Louis Cardinals', 'short_name' => 'STL Cardinals', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Tampa Bay Rays', 'short_name' => 'TB Rays', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Texas Rangers', 'short_name' => 'TEX Rangers', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Toronto Blue Jays', 'short_name' => 'TOR Blue Jays', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
//        DB::table('teams')->insert(['name' => 'Washington Nationals', 'short_name' => 'WSH Nationals', 'league' => 'MLB', 'created_at' => NOW(), 'updated_at' => NOW(),]);
    }
}
